# Generated by Django 5.1.2 on 2024-10-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_seller_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auction.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
