# Generated by Django 5.1.2 on 2024-11-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_item_auction_auction_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
