# Generated by Django 5.1.2 on 2024-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seller_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.IntegerField()),
                ('bid_time', models.DateTimeField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_id', models.IntegerField()),
                ('bidder_id', models.IntegerField()),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_description', models.TextField()),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
