# Generated by Django 5.1.2 on 2024-11-14 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_deletedauction_deletedbid_deleteditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedauction',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deletedbid',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
