# Generated by Django 5.1.2 on 2024-11-14 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_deletedauction_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedauction',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='deletedbid',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='deleteditem',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
